version: '3'
services:
  nginx:
      image: nginx:latest
      restart: unless-stopped
      tty: true
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/my-app.conf
        - ./logs/nginx:/var/log/nginx
        - ./nginx-logrotate.conf:/etc/logrotate.d/nginx-logrotate.conf
      ports:
        - "80:80"
      depends_on:
        - dfms-backend
        - dfms-frontend
  dfms-frontend:
    image: capstone/fe
    restart: unless-stopped
    tty: true
    ports:
      - "70:70"
  
  dfms-backend:
    image: capstone/dfms:latest
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Ho_Chi_Minh
      MYSQL_HOST: db_dfms
      MYSQL_PORT: 3306
      MYSQL_USER: dairyfarm2024
      MYSQL_PASSWORD: dairyfarm2003
      MYSQL_DATABASE: dfms
      VERIFY_URL: http://34.124.196.11:8080/api/v1/users/verify
      FIREBASE_CONFIG: '{"type":"service_account","project_id":"dfms-268e0","private_key_id":"5f06c2969800564c3bb8035593b025b0b2f00249","private_key":"-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC0SYCA4HkhM5zK\ng6SIZhzYw2IlSAeLlnWwqfj6i5ofxKuGrO+2yPM1656vwOwZXelkWM+MU3dRtZLf\nwHNL5G+dFVmur5bK5PRfPhtToqHr5zOzjDFFNCehPKlaLbXLRsmO9/81mlu2Is0i\nCK8pLlKt/Dv0ppWJB1r89c7H3YtNrcKlnZ1/1Og0jja3qlklPUYQsC8nB6sAc7Yf\n0OV61W2FnTvSW9G2VjGy+jONfoBddysEsI18hHJMjXVY7K+R2h+bnWjHP0dt21+t\nKa+5WoS+2RdwKLz04WLx3J3Au5iX1wPcgfvjKTRUsSCKaewvr0ts+tGz62+SCqPJ\nqYZgkx/JAgMBAAECggEACOHxNDuH3eN1QQLgHAqAUKUjV6GXO5QMohX+l77BxHk6\nZHHuhDOdstIN0rkSeN2umak76patk44UZmezPPGl/STEf/Qtqm5bsVPPevarLyk7\ndYgKYM9xxc9feBTpKgXuEtgnQxMWNZPv37jy6ZH02v0i0BcJpl0OKTxY9Vh2D1Wt\nD95RfQTWdO4/6baknaYrgbAyE/XWGupbKQpN+AqMPF9kDZMmtPfaER2Fzca0kfGC\nyZRzIy9TD8BTBLlmEB7yNemOkMgKhb25XQRN/62LgdsKvLze5gqH68ywoFcw9mtB\nqiikMq00pJDMMP3VoD8BB7odvQKIznuCkWsZ5fPKrQKBgQDkDwlyJ9CPw6ZqcvOy\naVZlwe8mScyPE2mn5aGSY/BHHUAp9LnphCkeRRZeH5gYz/G5oDOQM9GcJyv9Y/Zm\nmNPUPI+agSK09uwn+aS4PwYyst/IbYmgTU1XNtfd0mVX3ucLCZ/wKitQ2twxbG3M\nN9Jw7L4JLORtMRsy5KH1aGo+5QKBgQDKYCEDuizEB7yEmoxoOmUGx2gFyZx6nPiD\nIUXmTEloqaKKDJllwCWg41wt7sX8cB7qgGmilfNjiGjziPY077tfqsFzRy1sYe3D\nLBVOwPBn1WhXOLkzdJPMkEW7VYq1wj9lDi2V+niYzkTGEL0W+aHeeXiPsAXOjd0Q\nLu1u8eWrFQKBgFehJ4IDpnH3PZSdguJE83u6HwhZRw6a6PgolgLH/+Vzado1PNJr\ng9krtsKH5Utza3BmDCoWny4fJxoANQeLJanhc1Rs1kcuseNSW2aoYNtOPAqpfD5q\nNZOTcTK8y1AOSDzHf/sqWOaCkiUzgqT7thLKBONFqqgCPG87xrejXV+5AoGBAKjP\nNNrSEoNWXLdT32kVxK256hhhy0gv5dAkEhV/bwCB99YlmlNYy0qAPKUH9liTAgbk\nJLl9UW+mGr2CcrVHf8nWOtW4+rfcnCLgg8mUgTRrvER9SWcViC/r7G7OdQ0WQiE+\niWIAc1YrQQzia4hdpNtaAeoBj2ZzyYG1U1LnLofdAoGAICwfXGkSPbpL0vvGspKm\n26VAvQjZNtJlxnTo4aT7VZgBZqwLki4IGTLk35EQmrf68lwjn7xYwm5PnA/bfbgV\nFA1HWdln4yV320VOi/luOc9KkjiOdM10bB9zByjnCuKMzwoS3zMFjsjaaJ+NrSdW\nGe2hRMbGPxah1wabpw7nGb4=\n-----END PRIVATE KEY-----\n","client_email":"firebase-adminsdk-fbsvc@dfms-268e0.iam.gserviceaccount.com","client_id":"115530070335163499477","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":"https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40dfms-268e0.iam.gserviceaccount.com","universe_domain":"googleapis.com"'
    depends_on:
      - db_dfms
    volumes:
      - /root/images:/app/uploads

  db_dfms:
    image: mysql:latest
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: SWD392
      MYSQL_DATABASE: dfms
      MYSQL_USER: dairyfarm2024
      MYSQL_PASSWORD: dairyfarm2003
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
